// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeTube
{
    internal sealed partial class Vsix
    {
        public const string Id = "CodeTube.f305613a-4b47-4255-9eef-9087c2ab280e";
        public const string Name = "CodeTube";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Himanshu kumar Sharma";
        public const string Tags = "";
    }
}
