// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeTube
{
    internal sealed partial class Vsix
    {
        public const string Id = "CodeTube.cf725c47-fda3-4af1-a816-3ee96f51225d";
        public const string Name = "CodeTube";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Himanshu kumar Sharma";
        public const string Tags = "";
    }
}
